library(kohonen)
data("wines")
set.seed(1)
som.wines=som(scale(wines),grid=somgrid(5,5,"hexagonal"))
dim(getCodes(som.wines))
plot(som.wines,main = "wine data kohonen SOM")
graphics.off()
par(mfrow=c(1,1))
plot(som.wines,type = "changes",main = "wine data: SOM")
training<-sample(nrow(wines),150)#设置从1-150的随机数
Xtraining=scale(wines[training,])
Xtest=scale(wines[-training,],center = attr(Xtraining,"scaled:center"),
            scale = attr(Xtraining,"scaled:scale"))
trainingdata=list(measurements=Xtraining,vintages=vintages[training])   
testdata=list(measurements=Xtest,vintages=vintages[-training])
mygrid=somgrid(5,5,"hexagonal")
model=supersom(trainingdata,grid = mygrid)
som.prediction=predict(model,testdata)
table(vintages[-training],som.prediction$predictions[["vintages"]])
